### ISSUE TITLE
Unhandled Exception: Concurrent modification during iteration

### ISSUE THREAD

**Issue by ivantrave** [ueman/screenrecorder#13]
I am new to Flutter and I am trying to use this dependency to record the screen.

The following exception is being thrown after calling the `export` function:

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Concurrent modification during iteration: Instance(length:7) of '_GrowableList'.
#0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
#1      ScreenRecorderController.export (package:screen_recorder/src/screen_recorder.dart:111:25)
<asynchronous suspension>
```

The code to reproduce it:

```
  @override
  Widget build(BuildContext context) {
    ...
    return IconButton(
      icon: IconBuilder.get(...) :
      onPressed: () async {
        if (widget.recordController == null) {
          gameState.stop();
          return;
        }

        if (gameState.isPlaying) {
          gameState.stop();
          var gif = await widget.recordController!.export();

          showDialog(
            context: context,
            builder: (context) {
              return AlertDialog(
                content: Image.memory(Uint8List.fromList(gif!)),
              );
            },
          );

          return;
        }

        gameState.play();
        widget.recordController!.start();
      },
    );
  }
```

Any suggestion?

Many thanks

**Comment by ivantrave** [comment]
Nevermind. Missed the call to: `widget.recordController!.stop();`
